### ISSUE TITLE
Replace the array with the readfile function

### ISSUE THREAD

**Issue by mrbin-99** [dievus/PythonCreateYourOwnSeries#1]
Hi Joe,
I hope that this ok to submit an  
I recommend adding a read option from a file of the subdomains array with the function readfile, 
It will be much more convenient
best regards
Bin

try:
    domain = sys.argv[1]
except IndexError:
    print('Syntax Error - python3 subdomenum.py <domain>')

# Using readlines()
file1 = open('path to file', 'r')
subdomain_array = file1.readlines()

def main():
    subdomain_store = []
    for subdoms in subdomain_array:
        try:
            subdoms = subdoms.strip()
            ip_value = dns.resolver.resolve(f'{subdoms}.{domain}', 'A')
            if ip_value:
                subdomain_store.append(f'{subdoms}.{domain}')
                if f"{subdoms}.{domain}" in subdomain_store:
                    print(f'{subdoms}.{domain} valid')
                else:
                    pass
        except dns.resolver.NXDOMAIN:
            pass
        except dns.resolver.NoAnswer:
            pass
        except KeyboardInterrupt:
            quit()

main()

**Comment by dievus** [comment]
Hi there. This is just to go along with the videos and is taught very simplistically so people who may have never had interaction with these processes can see some basics.  

I appreciate you contributing the code, but nothing will be added so it doesn't create issues between video and scripts.

If you refer to my full tool you'll see that what you're suggesting is implemented in it. https://github.com/dievus/msdnsscan/blob/main/msdnsscan.py

**Comment by mrbin-99** [comment]
OK, thanks for letting me know.
have a great day and keep on the great work
