### ISSUE TITLE
DNS Type Errror

### ISSUE THREAD

**Issue by matticamp** [dievus/PythonCreateYourOwnSeries#2]
python3 demodns.py youtube.com
A Records
------------------------------
172.217.5.14
AAAA Records
------------------------------
2607:f8b0:4009:817::200e
Traceback (most recent call last):
  File "demodns.py", line 10, in <module>
    answer = dns.resolver.resolve(domain,records)
  File "/home/matt/.local/lib/python3.8/site-packages/dns/resolver.py", line 1305, in resolve
    return get_default_resolver().resolve(qname, rdtype, rdclass, tcp, source,
  File "/home/matt/.local/lib/python3.8/site-packages/dns/resolver.py", line 1159, in resolve
    resolution = _Resolution(self, qname, rdtype, rdclass, tcp,
  File "/home/matt/.local/lib/python3.8/site-packages/dns/resolver.py", line 524, in __init__
    rdtype = dns.rdatatype.RdataType.make(rdtype)
  File "/home/matt/.local/lib/python3.8/site-packages/dns/enum.py", line 69, in make
    return cls.from_text(value)
  File "/home/matt/.local/lib/python3.8/site-packages/dns/enum.py", line 43, in from_text
    raise cls._unknown_exception_class()
dns.rdatatype.UnknownRdatatype: DNS resource record type is unknown.

**Comment by dievus** [comment]
Not sure what the question is here. 

I just tested it against Youtube and it worked fine. My only guess is it has something to do with your DNS provider. The below is the exact code copied directly from the repository.

```
PS C:\Users\jwhel\Desktop\Projects\Python Video Projects> python3 .\dnsenum.py youtube.com

A Records
------------------------------
172.217.2.110

AAAA Records
------------------------------
2607:f8b0:4004:801::200e

NS Records
------------------------------
ns3.google.com.
ns1.google.com.
ns2.google.com.
ns4.google.com.

MX Records
------------------------------
0 smtp.google.com.

SOA Records
------------------------------
ns1.google.com. dns-admin.google.com. 462102254 900 900 1800 60

TXT Records
------------------------------
"facebook-domain-verification=64jdes7le4h7e7lfpi22rijygx58j1"
"v=spf1 include:google.com mx -all"
"google-site-verification=QtQWEwHWM8tHiJ4s-jJWzEQrD_fF3luPnpzNDH-Nw-w"```
